version: '2'
services:
    tasksmongo-app:
        image: tasksmongo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://tasksmongo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=tasksmongo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tasksmongo-mongodb:
        extends:
            file: mongodb.yml
            service: tasksmongo-mongodb
