version: '2'
services:
    tasksmongo-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/tasksmongo/mongodb/:/data/db/
